### ISSUE TITLE
when i train to epoch 1464 , it always stuck

### ISSUE THREAD

**Issue by mmwan101010** [jhcknzzm/Federated-Learning-Backdoor#8]
when i train to epoch 1464,it always stuck like that....
but i dont know why,how can i resolve it?Did you in this case before?

![f2d7dcc8ff2904a7ff9af9f2db5354a](https://user-images.githubusercontent.com/43236705/188301048-9f10122d-9f2d-421f-974a-956bc6b600a3.jpg)

**Comment by mmwan101010** [comment]
what should i do ? please help : (

**Comment by jhcknzzm** [comment]
I haven't had this problem before. However, I guess it is because when users are randomly sampled, the data of a sampled user is very small, and the condition of line 277 in the train_funcs.py cannot be satisfied, so the loss is not calculated. Maybe you can comment out the if statement on lines 277-278 in the train_funcs.py.

**Comment by jhcknzzm** [comment]
You can also initialize loss=0.0 before the loop on line 274 in the train_funcs.py.

**Comment by mmwan101010** [comment]
thank you for your reply , i modify the   batch_size: 20 to 15 &&  participant_population: 8000 to 6000   in words_reddit_lstm.yaml and then the issue be resolved.
